title: vkt.sh
description: > # this means to ignore newlines until "baseurl:"
  Software development
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vkt.sh" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: victorkohl

# Author Settings
author: Victor Tavares
author-img: 7974934.png
about-author: I am a software engineer focusing on back-end development.
social-twitter: victorkohl
social-github: victorkt
social-linkedin: vktavares
#social-email: # add your Email address

# Disqus
discus-identifier: vkt-sh

# Tracker
analytics: UA-134847163-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
